# .gitlab-ci.yml
stages:
  - install
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install uv==0.6.12 --user
  - ~/.local/bin/uv sync --frozen

install:
  stage: install
  script:
    - echo "Dependencies installed."

unit_tests:
  stage: test
  script:
    - ~/.local/bin/uv run pytest tests/unit

integration_tests:
  stage: test
  script:
    - ~/.local/bin/uv run pytest tests/integration
